version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  build_project:
    working_directory: ~/intro-app
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: yarn
      - run: 
          name: Building project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run: echo $AWS_SECRET_ACCESS_KEY
      - run: echo ${AWS_SECRET_ACCESS_KE}
      - run:
          name: Upload file to S3
          command: aws s3 sync ./build/ s3://intro-app --delete

workflows:
  run:
    jobs:
      - build_project
      - deploy_project:
          context: aws-context
          requires:
            - build_project