version: 2.1
jobs:
  intro-app:
    docker:
      - image: circleci/node:14.10
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run: yarn test
    - run: sudo apt-get update && sudo apt-get install -y python-dev
    - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
    - run: sudo python get-pip.py
    - run: sudo pip install awscli --upgrade
    - run: aws --version
    - run: aws s3 ls
    - run: yarn run deploy

workflows:
  run:
    jobs:
      - espace-client